// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE0oH607eFab99YevTC6S_EvPEZivJct8',
    appId: '1:184777485102:web:52033778476730677068bf',
    messagingSenderId: '184777485102',
    projectId: 'plustik-fdd2a',
    authDomain: 'plustik-fdd2a.firebaseapp.com',
    storageBucket: 'plustik-fdd2a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTu3UzUfWIZnW1BsY02t003KQbIjTZBoE',
    appId: '1:184777485102:android:29b13d501dae92057068bf',
    messagingSenderId: '184777485102',
    projectId: 'plustik-fdd2a',
    storageBucket: 'plustik-fdd2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjh1oKlknxA2sfyc6E9Jr6GceAEIm62cc',
    appId: '1:184777485102:ios:e91b9f462d61b6937068bf',
    messagingSenderId: '184777485102',
    projectId: 'plustik-fdd2a',
    storageBucket: 'plustik-fdd2a.appspot.com',
    iosBundleId: 'com.example.plustik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjh1oKlknxA2sfyc6E9Jr6GceAEIm62cc',
    appId: '1:184777485102:ios:6ddcbe81dd3865d27068bf',
    messagingSenderId: '184777485102',
    projectId: 'plustik-fdd2a',
    storageBucket: 'plustik-fdd2a.appspot.com',
    iosBundleId: 'com.example.plustik.RunnerTests',
  );
}
